// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc-nlSEZLuYxcaXmqNb8qlKSlw3dHrnb8',
    appId: '1:1039154049310:web:2693c4d89e36ea2239d90f',
    messagingSenderId: '1039154049310',
    projectId: 'moodswing-b3a8f',
    authDomain: 'moodswing-b3a8f.firebaseapp.com',
    storageBucket: 'moodswing-b3a8f.firebasestorage.app',
    measurementId: 'G-7P8KLKKLZ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMj5HWyb2AkF7nrXgDwKEe4_92AL66xd8',
    appId: '1:1039154049310:android:24e1f3d100bd384539d90f',
    messagingSenderId: '1039154049310',
    projectId: 'moodswing-b3a8f',
    storageBucket: 'moodswing-b3a8f.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCc-nlSEZLuYxcaXmqNb8qlKSlw3dHrnb8',
    appId: '1:1039154049310:web:f0a7a9e96769f37839d90f',
    messagingSenderId: '1039154049310',
    projectId: 'moodswing-b3a8f',
    authDomain: 'moodswing-b3a8f.firebaseapp.com',
    storageBucket: 'moodswing-b3a8f.firebasestorage.app',
    measurementId: 'G-D4STN2KJ2Y',
  );
}
